services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Fixtures\:
        resource: '../tests/Fixtures'
        tags: ['doctrine.fixture.orm']

    Liip\TestFixturesBundle\Services\DatabaseTools\AbstractDatabaseTool:
        alias: Liip\TestFixturesBundle\Services\DatabaseTools\ORMSqliteDatabaseTool
        public: true

